const LOGIN: string = "LOGIN";
const FETCH_LOGIN: string = "FETCH_LOGIN";
const FETCH_REGISTER: string = "FETCH_REGISTER";
const SET_AUTH_MESSAGE: string = "SET_SERVER_MESSAGE";
const FETCH_CONFIRM_REGISTER: string = "FETCH_CONFIRM_REGISTER";
const LOGOUT: string = "LOGOUT";
const SET_AUTH_ERROR: string = "SET_AUTH_ERROR_MESSAGE";
const GET_AUTH_USER: string = "GET_AUTH_USER";

export {
  LOGIN,
  FETCH_LOGIN,
  LOGOUT,
  FETCH_REGISTER,
  FETCH_CONFIRM_REGISTER,
  GET_AUTH_USER,
  SET_AUTH_ERROR,
  SET_AUTH_MESSAGE,
};
