const FETCH_TASKS: string = "FETCH_TASKS";
const REQUEST_TASKS_SUCCESS: string = "REQUEST_TASKS_SUCCESS";
const FETCH_CURRENT_TASK: string = "FETCH_CURRENT_TASK";
const REQUEST_CURRENT_TASK_SUCCESS: string = "REQUEST_CURRENT_TASK_SUCCESS";
const FETCH_ADD_TASKS: string = "FETCH_ADD_TASKS";
const ADD_TASKS: string = "ADD_TASKS";
const SET_TASKS_ERROR: string = "SET_TASKS_ERROR";
const SET_TASKS_LOADING: string = "SET_TASKS_LOADING";
const FETCH_DELETE_TASKS: string = "FETCH_DELETE_TASKS";
const DELETE_TASKS: string = "DELETE_TASKS";
const FETCH_UPDATE_TASKS: string = "FETCH_UPDATE_TASKS";
const UPDATE_TASKS: string = "UPDATE_TASKS";
const SET_TASKS_MESSAGE: string = "SET_TASKS_MESSAGE";

export {
  FETCH_TASKS,
  REQUEST_TASKS_SUCCESS,
  FETCH_CURRENT_TASK,
  REQUEST_CURRENT_TASK_SUCCESS,
  FETCH_ADD_TASKS,
  ADD_TASKS,
  SET_TASKS_ERROR,
  SET_TASKS_LOADING,
  FETCH_DELETE_TASKS,
  DELETE_TASKS,
  FETCH_UPDATE_TASKS,
  UPDATE_TASKS,
  SET_TASKS_MESSAGE,
};
