const FETCH_PROJECTS: string = "FETCH_PROJECTS";
const REQUEST_PROJECTS_SUCCESS: string = "REQUEST_PROJECTS_SUCCESS";
const FETCH_CURRENT_PROJECT: string = "FETCH_CURRENT_PROJECT";
const REQUEST_CURRENT_PROJECT_SUCCESS: string =
  "REQUEST_CURRENT_PROJECT_SUCCESS";
const FETCH_ADD_PROJECTS: string = "FETCH_ADD_PROJECTS";
const ADD_PROJECTS: string = "ADD_PROJECTS";
const SET_PROJECT_ERROR: string = "SET_PROJECT_ERROR";
const SET_PROJECTS_LOADING: string = "SET_PROJECTS_LOADING";
const FETCH_DELETE_PROJECTS: string = "FETCH_DELETE_PROJECTS";
const DELETE_PROJECTS: string = "DELETE_PROJECTS";
const FETCH_UPDATE_PROJECTS: string = "FETCH_UPDATE_PROJECTS";
const UPDATE_PROJECTS: string = "UPDATE_PROJECTS";
const SET_PROJECTS_MESSAGE: string = "SET_PROJECTS_MESSAGE";
export {
  FETCH_PROJECTS,
  FETCH_CURRENT_PROJECT,
  REQUEST_PROJECTS_SUCCESS,
  SET_PROJECT_ERROR,
  REQUEST_CURRENT_PROJECT_SUCCESS,
  FETCH_ADD_PROJECTS,
  ADD_PROJECTS,
  DELETE_PROJECTS,
  SET_PROJECTS_LOADING,
  FETCH_DELETE_PROJECTS,
  UPDATE_PROJECTS,
  FETCH_UPDATE_PROJECTS,
  SET_PROJECTS_MESSAGE,
};
