const FETCH_PROJECTS: string = "FETCH_PROJECTS";
const FETCH_CURRENT_PROJECT: string = "FETCH_CURRENT_PROJECT";
const FETCH_ADD_PROJECT: string = "FETCH_ADD_PROJECT";
const REQUEST_PROJECTS_SUCCESS: string = "REQUEST_PROJECT_SUCCESS";
const REQUEST_CURRENT_PROJECT_SUCCESS: string = "REQUEST_PROJECT_SUCCESS";
const REQUEST_PROJECT_ERROR: string = "SET_SERVER_MESSAGE";

export {
  FETCH_PROJECTS,
  FETCH_CURRENT_PROJECT,
  REQUEST_PROJECTS_SUCCESS,
  REQUEST_PROJECT_ERROR,
  REQUEST_CURRENT_PROJECT_SUCCESS,
  FETCH_ADD_PROJECT,
};
